version: "2"

services:
  db:
    container_name: django_db
    image: postgres:11.2
    volumes:
      - django_data_volume:/var/lib/postgresql/data
    mem_limit: 64m
  rest_api:
    container_name: django_rest_api
    build:
      context: .
      dockerfile: DockerfilePython
    volumes:
      - ./code/django_rest_api:/code
    tty: true
    ports:
      - 8000:8000
      # - 80:8000
    depends_on:
      - db
    mem_limit: 64m
  web_front:
    container_name: django_web_front
    build:
      context: .
      dockerfile: DockerfileNode
    volumes:
      - ./code/django_web_front:/code
    tty: true
    ports:
      # - 3000:3000
      - 80:3000
    depends_on:
      - rest_api
    mem_limit: 256m
volumes:
  django_data_volume:
